#!/usr/bin/env python3
import sys
import requests
import re

# ============================================================
# Pattern Detector (from your previous work)
# ============================================================

def detect_sas_patterns(sas_code: str) -> dict:
    flags = {
        "RETAIN": False,
        "BY": False,
        "FIRST_LAST": False,
        "ARRAY": False,
        "MACRO": False,
        "COMPLEXITY_SCORE": 0
    }
    
    if re.search(r'\bretain\b', sas_code, re.IGNORECASE):
        flags["RETAIN"] = True
        flags["COMPLEXITY_SCORE"] += 2
    
    if re.search(r'\bby\s+\w+', sas_code, re.IGNORECASE):
        flags["BY"] = True
        flags["COMPLEXITY_SCORE"] += 1
    
    if re.search(r'\bfirst\.\w+|\blast\.\w+', sas_code, re.IGNORECASE):
        flags["FIRST_LAST"] = True
        flags["COMPLEXITY_SCORE"] += 2
    
    if re.search(r'\barray\b', sas_code, re.IGNORECASE):
        flags["ARRAY"] = True
        flags["COMPLEXITY_SCORE"] += 3
    
    if re.search(r'%', sas_code):
        flags["MACRO"] = True
        flags["COMPLEXITY_SCORE"] += 2
    
    # Routing decision
    if flags["RETAIN"] and flags["BY"] and flags["FIRST_LAST"]:
        flags["ROUTING"] = "MANUAL_REVIEW"
        flags["REASON"] = "Complex RETAIN+BY+FIRST pattern"
    elif flags["RETAIN"] and flags["BY"]:
        flags["ROUTING"] = "CAUTION"
        flags["REASON"] = "RETAIN with BY (no FIRST) - attempt with caution"
    elif flags["COMPLEXITY_SCORE"] >= 3:
        flags["ROUTING"] = "CAUTION"
        flags["REASON"] = f"Multiple patterns (score {flags['COMPLEXITY_SCORE']})"
    else:
        flags["ROUTING"] = "AUTO_LLM"
        flags["REASON"] = "Simple pattern - safe for auto-translation"
    
    return flags

# ============================================================
# Translation Function
# ============================================================

def translate_sas(sas_code: str) -> str:
    prompt = f"""Convert this SAS code to Python using polars.
Output only the Python code, no explanations, no markdown formatting.

SAS CODE:
{sas_code}

PYTHON CODE:"""

    response = requests.post(
        "http://localhost:8080/v1/chat/completions",
        headers={"Content-Type": "application/json"},
        json={
            "model": "qwen2.5-coder:7b",
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.1,
            "max_tokens": 2000
        },
        timeout=120
    )

    if response.status_code != 200:
        raise RuntimeError(f"Server error: {response.text}")

    output = response.json()["choices"][0]["message"]["content"]

    if "```python" in output:
        output = output.split("```python")[1].split("```")[0]
    elif "```" in output:
        output = output.split("```")[1].split("```")[0]

    return output.strip()

# ============================================================
# Main
# ============================================================

def main():
    if len(sys.argv) < 2:
        print("Usage: python sas2py_router.py <input.sas>")
        sys.exit(1)

    input_path = sys.argv[1]

    with open(input_path, 'r') as f:
        sas_code = f.read()

    print("🔍 Analyzing SAS code...")
    result = detect_sas_patterns(sas_code)

    print(f"   RETAIN: {result['RETAIN']}")
    print(f"   BY: {result['BY']}")
    print(f"   FIRST/LAST: {result['FIRST_LAST']}")
    print(f"   Routing: {result['ROUTING']}")
    print(f"   Reason: {result['REASON']}")

    if result['ROUTING'] == "MANUAL_REVIEW":
        print("❌ MANUAL REVIEW REQUIRED")
        output_path = input_path.replace('.sas', '_MANUAL.py')
        with open(output_path, 'w') as f:
            f.write("# MANUAL REVIEW REQUIRED\n")
            f.write(f"# Reason: {result['REASON']}\n")
            for line in sas_code.split('\n'):
                f.write(f"# {line}\n")
        print(f"📝 Placeholder written to: {output_path}")
        sys.exit(0)

    if result['ROUTING'] == "CAUTION":
        print("⚠️ CAUTION - Review output carefully")
        proceed = input("   Continue? (y/n): ")
        if proceed.lower() != 'y':
            print("❌ Aborted.")
            sys.exit(0)

    print("🤖 Translating...")
    python_code = translate_sas(sas_code)

    output_path = input_path.replace('.sas', '.py')
    with open(output_path, 'w') as f:
        f.write("# Generated by sas2py_router\n")
        f.write(f"# Routing: {result['ROUTING']}\n")
        f.write("import polars as pl\n\n")
        f.write(python_code)

    print(f"✅ Wrote {output_path}")

if __name__ == "__main__":
    main()
