#!/usr/bin/env python3
"""SAS to Python translator with syntax validation"""

import subprocess
import sys
import ast

def translate_sas_to_python(sas_code: str, model: str = "qwen2.5-coder:7b") -> str:
    prompt = f"""Convert this SAS code to Python using polars. 
Output only the Python code, no explanations, no markdown formatting.

SAS CODE:
{sas_code}

PYTHON CODE:"""
    
    result = subprocess.run(
        ["ollama", "run", model, prompt],
        capture_output=True,
        text=True,
        timeout=120
    )
    
    if result.returncode != 0:
        raise RuntimeError(f"Ollama failed: {result.stderr}")
    
    output = result.stdout
    if "```python" in output:
        output = output.split("```python")[1].split("```")[0]
    elif "```" in output:
        output = output.split("```")[1].split("```")[0]
    
    return output.strip()

def validate_python_syntax(code: str) -> tuple[bool, str]:
    """Check if Python code is syntactically valid"""
    try:
        ast.parse(code)
        return True, "Syntax OK"
    except SyntaxError as e:
        return False, f"Line {e.lineno}: {e.msg}"

def main():
    if len(sys.argv) < 2:
        print("Usage: python sas2py_with_validate.py <input.sas> [model]")
        sys.exit(1)
    
    input_path = sys.argv[1]
    model = sys.argv[2] if len(sys.argv) > 2 else "qwen2.5-coder:7b"
    
    with open(input_path, 'r') as f:
        sas_code = f.read()
    
    print(f"Translating {input_path} with {model}...")
    python_code = translate_sas_to_python(sas_code, model)
    
    # Validate syntax
    is_valid, msg = validate_python_syntax(python_code)
    if not is_valid:
        print(f"⚠️ SYNTAX ERROR: {msg}")
        print("The generated code may need manual fixes.")
    else:
        print("✅ Syntax check passed")
    
    output_path = input_path.replace('.sas', '.py')
    with open(output_path, 'w') as f:
        f.write("# Generated by sas2py\n")
        f.write("import polars as pl\n\n")
        f.write(python_code)
    
    print(f"✅ Wrote {output_path}")

if __name__ == "__main__":
    main()
