# Generated by sas2py_router
# Routing: AUTO_LLM
import polars as pl

import polars as pl

df = pl.read_csv("have.csv")
df = df.with_column(pl.when(df["age"] > 18).then(1).otherwise(0).alias("adult"))
df.write_csv("want.csv")