# Generated by sas2py_router
# Routing: AUTO_LLM
# Reason: Simple pattern - safe for auto-translation
import polars as pl

import polars as pl

df_want = df_have.with_column(pl.when(df_have['age'] > 18).then(1).otherwis[20D[K
18).then(1).otherwise(None).alias('adult'))