# Generated by sas2py
import polars as pl

import polars as pl

# Assuming 'raw_data' is a DataFrame in Polars with columns 'age', 'sales',[8D[K
'sales', and 'region'
summary = raw_data.filter(pl.col('age') > 18).groupby('region').agg([
    pl.col('sales').sum().alias('total_sales'),
    (pl.col('sales') / 30).alias('monthly_avg')
])